apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - app-metallb-system.yaml  
patchesStrategicMerge:
  - argocd-server-service.yaml
  - argocd-configmap.yaml
